### ISSUE TITLE
Hire a summer intern

### ISSUE THREAD

**Issue by dkhowala** [openstax/ux#78]
### Tasks

- [x] Post an opening on handshake
- [x] Prepare questions for the interview with the team
- [x] review and invite candidates for interview
- [x] Schedule phone interviews with shortlisted candidates
- [x] Conduct in-person interviews, if required
- [x] Review with team
- [x] Send offer letter to selected candidate
- [x] Share candidate details with HR and Finance
